### ISSUE TITLE
improve grouping in macros page

### ISSUE THREAD

**Issue by magnetophon** [magnetophon/DigiDrie#14]
make it `macros->1->env->0` same for the rest of the macros

**Comment by magnetophon** [comment]
@ryukau What should I do with the main macro slider on that page?

**Comment by ryukau** [comment]
`macros->1->macro` is an option.

Another idea is changing tab name `macros` to `modulation`. So it becomes `modulation->1->macro`. This change makes using search functionality in text editor more convenient. (Searching `macro` highlights both `macros` and `macro`.)

**Comment by magnetophon** [comment]
I think `modulation` is a bit unclear, how about `macros masters`?

**Comment by ryukau** [comment]
`macros masters` don't solve the searching problem. In this case, I'm OK to leave `macros` as is.

**Comment by magnetophon** [comment]
Done.
Let me know if I forgot anything.
