### ISSUE TITLE
Naming of Moog

### ISSUE THREAD

**Issue by ryukau** [magnetophon/DigiDrie#20]
Just to make sure, is it really derived from Moog filter? If that's not the case, I think it's better to use `SVF` for the name.

At least from the code, it looks like basic SVF lowpass (linear 2-pole lowpass).

**Comment by magnetophon** [comment]
[Done](https://github.com/magnetophon/DigiDrie/commit/ec9dca0213ec63d9e26157ff3d8e73ab9f94dd31).

**Comment by magnetophon** [comment]
[Done](https://github.com/magnetophon/DigiDrie/commit/ec9dca0213ec63d9e26157ff3d8e73ab9f94dd31).
