### ISSUE TITLE
Experiment: remove variable number of macros, use double crossfade instead

### ISSUE THREAD

**Issue by magnetophon** [magnetophon/DigiDrie#21]
In [this branch](https://github.com/magnetophon/DigiDrie/tree/double_crossfade), I implemented the double cross-fade you suggested.

The cross-fade sliders are on the modulation page and are still called macro.
If we go with this architecture I will rename them of course.

In the GUI, I think they should become an XY-pad.

Please test this branch and let me know what you think.

My opinion:

Pro:
- When all the cross-fade sliders are at 0 or 1, you hear the settings of one of the "presets".
  With the system currently in the master branch, you hear an interpolation when more then one slider is at 1.
- 2 sliders control 4 presets, vs 3 sliders control 4 presets in the master branch 
- Much faster compile
- Slightly less CPU usage

Con:
- Fixed number of macros.
 But:
  - For most cases, 4 sounds is enough to morph between.
  - In [this branch](https://github.com/magnetophon/DigiDrie/tree/3Dcrossfade), I implemented a 3D cross-fade: 8 sounds under 3 sliders. What do you think?

I think more then 8 sounds are overkill. Agree?

All in all, I think I like this setup better, but I want to hear your opinion and test some more myself.

My order of preference:
1) 3D cross-fade
2) 2D cross-fade
3) current master

**Comment by ryukau** [comment]
I tried double cross-fade version, and I like it a lot more than current `master`.

Order of preference:

1. 3D
2. 2D
3. master

3D one definitly provides the value, even considering the added complexity. It's just too fun.

For UI, 3 knobs for X, Y, Z is better in my opinion. If we go X-Y pad path, there needs to be 3 X-Y pad for cross-fade: top, front, and side view of a cube (like [this](https://technologystudent.com/designpro/ortho2.htm)). To me, 3 knobs are more intuitive than 3 X-Y pads. Also advanced user can map the parameters to some external X-Y pad controller.

> I think more then 8 sounds are overkill. Agree?

I agree.

**Comment by magnetophon** [comment]
How about an XY-pad plus a Z knob?

**Comment by ryukau** [comment]
That's OK to me. Also how about this?

![digidrie_xypad](https://user-images.githubusercontent.com/6243462/89976107-873dac00-dca2-11ea-9af9-546ea91c5da5.png)

At least on VST 3, DAW can provide context menu for plugin controls. For example, right clicking a plugin knob opens menus like "Automate parameter", "Link parameter to MIDI controller" and so on. That's also a reason I'd like to keep a knob for each axis.

**Comment by magnetophon** [comment]
That's perfect!  :rocket:

**Comment by magnetophon** [comment]
I merged this brach into master.
