### ISSUE TITLE
Resonant Tri oscillator stop entire output with feedback PM

### ISSUE THREAD

**Issue by ryukau** [magnetophon/DigiDrie#22]
Tested on following branch:

- `master`
- `double-crossfade`

Steps to reproduce:

1. Set `A->type` to one of the `Resonant Tri`.
2. Set `A->main->PM->macro1-2->macro1->PM A` greater than 1.

Once the sound is stopped, the synth does't recover even if changing the type from `Resonant Tri` to different one.

`Resonant Tri` doesn't stop when `PM A` is 0.5, but stops when `PM A` is around 0.6.

**Comment by magnetophon** [comment]
I can reproduce the issue, but I'm not sure how to find the root cause.

If we don't find the cause, we could just limit the amount of PM on this osc, but that's not a great solution.

**Comment by ryukau** [comment]
Link to `CZresTriangle` code: https://github.com/grame-cncm/faustlibraries/blob/c3cdf038115c4f1b8f808b098cb1aa813fb37480/oscillators.lib#L1358

```faust
resTriangle(fund,res) = select2(fund<.5, 2-(fund*2), fund*2)*INDEX*2-1
with {
  INDEX = ((fund*(res:max(1)))+1:ma.decimal)*2*ma.PI:cos*.5+.5;
};
```

If I understand correctly, `INDEX` is in [0, 1]. So the problem lies in `select2(fund<.5, 2-(fund*2), fund*2)`.

- When `fund < 0`, `fund*2` becomes negative, and output may become less than -1.
- When `fund > 1`, `2-(fund*2)` becomes negative, and output may become less than -1.

This is likely the root cause of problem. Feedbacking the `resTriangle` output into `fund` diverges output into `-inf`. Once infinity is propagated to another parts of the synth, some internal buffer stays `-inf` regardless of parameter change.

I don't see any solution other than limiting `fund` range. Perhaps some waveshaper can be used. We'd like to keep `fund` linear in range of [0, 1], so the easiest option I can think of is `fund - floor(fund)`.

**Comment by magnetophon** [comment]
That was indeed the problem.
Thanks for the trouble-shooting!
