### ISSUE TITLE
LV2 url points to LV2plugins repo

### ISSUE THREAD

**Issue by magnetophon** [magnetophon/DigiDrie#33]
Just a detail, but it's a bit confusing.

**Comment by ryukau** [comment]
Thanks for the catch! Fixed it in local. I'll push it when we solved following issue:

Do you have and idea for brand (or developer/maker) name? I also forgot to change it and still says "Uhhyou". However, it's better to have different brand name for DigiDrie.

If it takes some time to come up with name, I'll put "DigiDrie Team" as placeholder.

**Comment by magnetophon** [comment]
Some ideas:

Over the top:
- DMI, for: "Digital Magic Industries"

A friend of mine came up with:
- wavefunk  for the synth
- wavefunkers for us.

Unfortunately there is already https://wavefunk.xyz, a label.
Not sure if that's a problem.

Otherwise he suggested sinewavefunk and sinewavefunkers. 

I'm open to any name.

**Comment by magnetophon** [comment]
I also like: DigiDrie for the synth, cause it sounds like 303 in dutch.
We could call ourselves "Wavefunk Industries"

**Comment by ryukau** [comment]
To avoid name conflict to wavefunk, how about replacing wave to some other words related to wave? For example, tidal, tsunami and so on.

**Comment by magnetophon** [comment]
Hmm, maybe something less deadly?

How about (synth name + slogan):
## SineFu*ker
### because there are many ways to funk up a sine.

Or, slightly more deadly:
## SineFu*ker
### 6 million ways to funk up a sine, choose eight.

After the [famous sample](https://www.quora.com/Why-can-we-often-hear-6-million-ways-to-die-choose-one-in-lyrics-Where-does-this-sentence-sample-reference-come?share=1)

But that is probably too many puns and references.

We could replace the * with an `n`, if you wanna play safe.


Just brainstorming here...
And these are all synth names, not brands.

**Comment by ryukau** [comment]
Just in case, I can't understand the tone in English. There's just too much difference to my native language (Japanese), so I can't comment much about good or bad of a name. Though replacing * with c is probably not good idea, I guess.

For synth name, I'm OK with DigiDrie.

For brand name there are 3 candidates it seems.

1. Digital Magic Industries
2. Wavefunk Industries
3. SineFu*kers (or SineFu*k Industries)

I'm OK with 1 or 3. I also like 2, but name conflict is better avoided.

**Comment by magnetophon** [comment]
I like 1. the best.

**Comment by ryukau** [comment]
Fixed in master branch. (c04791bbb6d8b95a14d8e93e5e4d1ca7076af7fb)
