### ISSUE TITLE
Scaling of PM

### ISSUE THREAD

**Issue by ryukau** [magnetophon/DigiDrie#34]
PM value range was increased from [0, 1] to [-20, 20] in 55a7a1729e94c917119ad0be700f0fe491d729ae. So some S-curve scaling is probably better than `[scale:log]`.

@magnetophon Could you change scale of PMs to `[scale:spoly]`?

[SPolyScale](https://github.com/magnetophon/DigiDrie/blob/50b62442cfab967f1802b12a7bb3a3c2b288ad6f/plugin/dpf/common/dsp/scale.hpp#L108) is currently only usable S-curve scale in my code. The linked C++ code is complicated because of normalization of `x`. The computation of curve is like below:

```c++
// x is input, a is a curve tuning parameter.

if (x < 0)
  curve = -pow(x, a);
else
  curve = pow(x, a);
```

Suggestion for other S-curve is welcome.

**Comment by magnetophon** [comment]
[Done](https://github.com/magnetophon/DigiDrie/commit/076ad43b4560d0af189ac1747b3cf022c74ddc3e).

**Comment by ryukau** [comment]
Thanks for the change.

I now added SPolyScale support into master. PM knobs now have a bit of room around 12 o'clock.

**Comment by magnetophon** [comment]
Yes, much better!
