### ISSUE TITLE
Fast Parameter Mapping

### ISSUE THREAD

**Issue by ryukau** [magnetophon/DigiDrie#5]
Some parameter mappings are heavy. Especially when it involves math functions (`math.h`-Equivalent Primitives in Faust).

I can provide 2 possibilities to make parameter mapping faster.

## Map only at the start of current cycle
I'm not sure if there's Faust option for this, but the idea is to call heavy parameter mappings only in control rate, then smooth the parameter values in audio rate.

Consider Faust code like below:

```faust
value = pow(2, someParameter);
```

`pow` or other math functions are heavy if they are called for each frame.

To avoid this, we can change Faust code to just receive mapped value:

```faust
value = hslider(/* ... */);
```

Mapping will be done on C++ side:

```c++
value = pow(2, getSomeParameterFromUI());

for (int i = 0; i < frames; ++i) {
  faustDsp.value = smooth(value);
  out[i] = faustDsp.processOneFrame();
}
```

Think `smooth()` as equivalent of Faust `smooth`.

With this, we can avoid calling `pow` for all frames.

## Create faster approximation
Some functions may be replaced with faster and slightly inaccurate approximation.

For example, I'm using following filter for smoothing.

```c++
value += kp * (input - value);
```

`kp` changes cutoff frequency. Below is the exact function to map cutoff frequency in Hz to `kp`:

```c++
float cutoffToKp(float sampleRate, float cutoffHz)
{
  omega_c = 2 * pi * cutoffHz / sampleRate;
  y = 1 - cos(omega_c);
  return -y + sqrt((y + 2) * y);
}
```

There are `cos` and `sqrt`, so `cutoffToKp()` is heavy.

Approximation of the exact function:

```c++
float cutoffToKpRat2Approx(float sampleRate, float cutoffHz)
{
  float x = cutoffHz / sampleRate;
  return (
    - 0.0004930424721520979
    + 2.9650003823571467 * x
    + 1.8250079928630534 * x * x
  ) / (
      0.4649282844668299
    + 1.8754712250208077 * x
    + 3.7307819672604023 * x * x
  )
  + 0.0010604699447733293;
}
```

On my environment, the approximated function is around 3 times faster than the exact function. However, keep in mind that it will not always this fast when integrated into real code. It largely depends on how compiler optimize the code.

Below is the plot of the exact function and its approximation:

![lowpass_kp_approx](https://user-images.githubusercontent.com/6243462/89142672-0a645100-d583-11ea-827e-b04277fd4356.png)

Below is the error plot (`exact - approximation`):

![lowpass_kp_approx_error](https://user-images.githubusercontent.com/6243462/89142684-105a3200-d583-11ea-93a6-37ea69c26261.png)

Approximation is done by using [`scipy.optimize.curve_fit`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html). Let me know if you are interested in details. I'll provide more information.

**Comment by magnetophon** [comment]
> Map only at the start of current cycle

This is done by faust, as long as I make sure not to smooth too soon in the graph.
I asked on slack, and sletz confirmed this.

I tried to make sure I always smooth as late as possible, but maybe I missed some spots.

> Create faster approximation

IIUC, this can in theory be done by faust, up to a certain point, by compiling with ``-fm def``.
Unfortunately it doesn't work for this code, see [this issue](https://github.com/grame-cncm/faust/issues/472).

Have you seen any particular spots that can be approximated?

**Comment by ryukau** [comment]
> This is done by faust, as long as I make sure not to smooth too soon in the graph.
> I asked on slack, and sletz confirmed this.
> 
> I tried to make sure I always smooth as late as possible, but maybe I missed some spots.

This is really nice feature. I guess I have to look into faust more closely.

> IIUC, this can in theory be done by faust, up to a certain point, by compiling with -fm def.
> Unfortunately it doesn't work for this code, see this issue.
>
> Have you seen any particular spots that can be approximated?

Filter coefficients comes to my mind. Though, if the above optimization is already in place, this will not do much.

- https://github.com/magnetophon/DigiDrie/blob/998e42e29dbf12ebe772f90a04298d7f8c42fd35/lib/DigiDrie.lib#L480
- https://github.com/magnetophon/DigiDrie/blob/998e42e29dbf12ebe772f90a04298d7f8c42fd35/lib/DigiDrie.lib#L503
- https://github.com/magnetophon/DigiDrie/blob/998e42e29dbf12ebe772f90a04298d7f8c42fd35/lib/DigiDrie.lib#L664

**Comment by magnetophon** [comment]
> This is really nice feature. I guess I have to look into faust more closely.

This is one of many really nice features.
If faust seems interesting to you, it will probably be even better then you think.
Definitely check it out!!!

> Filter coefficients comes to my mind. Though, if the above optimization is already in place, this will not do much.

At which point do you think the smooth should be?
Afaik we don't want to smooth the ADSR's and LFO's, and we need to smooth the modulation mixer levels and the macros, no?
So iow there will always be audio rate modulation at all parameters: filters, oscillators and even the modulation mixer in macro-tab. 

Am I missing something?

Of course, when the parameters are static, you could stop calculating some stuff.
Not sure how to implement that though.

**Comment by magnetophon** [comment]
You even proposed to make all the parameters modulateable by the output of the oscillators.
When we get the CPU usage down enough, I'd like to implement that, probably via the macros.
What do you think?

**Comment by ryukau** [comment]
> At which point do you think the smooth should be?
> Afaik we don't want to smooth the ADSR's and LFO's, and we need to smooth the modulation mixer levels and the macros, no?
> So iow there will always be audio rate modulation at all parameters: filters, oscillators and even the modulation mixer in macro-tab.

Smoothing is mostly for control rate signals come from UI in my opinion. Under the veil, Faust's `smooth` is a 1-pole lowpass filter. So there may be use case of `smooth` to reduce high frequency of modulation signals.

In case of filter coefficients, there's likely 1 or 2 variables which are heavy to compute. They are likely monotonic, and using trigonometric functions in range of [0, pi] (likely an artifact of bilinear transform) and/or log (dB gain). So if those variables are computed in every frame, there's a room for speed up with approximation or smoothing.

I'm not sure if my approximation can compete to Faust `-fm def`. Though, if it's the equivalent of gcc `-ffast-math`, I'm pretty sure my approximation will be faster, because of reduced accuracy. That said it's always better to take benchmark. Once I figure out faustpp code generation, I'll experiment on this.

> You even proposed to make all the parameters modulateable by the output of the oscillators.
> When we get the CPU usage down enough, I'd like to implement that, probably via the macros.
> What do you think?

I'd love to have that, but some experimentation might be needed. 2nd or higher order filter may blow up when cutoff or Q are changing too fast.

**Comment by magnetophon** [comment]
I'm not following you.
If I smooth the control rate signals from the UI, I will get an audio rate signal, that is the point of smoothing.
If I then feed that audio rate signal to parameters, like the filter cutoff or Q, the filter coefficients *must* be computed every frame, right?

So that leaves us with optimizing by approximation.
I'll leave that to you!

**Comment by ryukau** [comment]
> I'm not following you.
> If I smooth the control rate signals from the UI, I will get an audio rate signal, that is the point of smoothing.
> If I then feed that audio rate signal to parameters, like the filter cutoff or Q, the filter coefficients must be computed every frame, right?

Probably my English is not good here. I agree with you.

> So that leaves us with optimizing by approximation.
> I'll leave that to you!

OK, I'll work on it later.
