### ISSUE TITLE
Parameter Names

### ISSUE THREAD

**Issue by ryukau** [magnetophon/DigiDrie#7]
I extracted parameters to `plugin/data/parameter.json` on `gui` branch. There are following problems.

### Duplication
There are duplicated parameter labels. Is it possible to remove duplication on Faust side?

### Convention
I'd like to have name start from highest hierarchy and end with lowest. This makes it easy to group parameters by sorting. For example,

- `GlobalMainEnv0`
- `OscillatorAMainCZMasterIndexAmount`
- `MacrosMacro0UpTime`

and so on.

### Character
I'm planning to use parameter label as C++ identifier. So it would be nice to use only `a-zA-Z0-9_` for label.

**Comment by magnetophon** [comment]
Great to see you got faustpp working! :tada:  

The parameter names are all unique when you take the path into account.
Can you do that?

I'm re-using a lot of code, including slider definitions.
I don't think it's a good idea to re-write the code with 700+ unique slider definitions!

Or did I misunderstand the request?

**Comment by ryukau** [comment]
So, it's hard to change UI label on Faust. The problem is that I couldn't extract GUI hierarchy of `h/v/tgroup` primitives with faustpp. I'll dig deeper on this.

**Comment by magnetophon** [comment]
Yeah, it wouldn't be fun to make them unique in faust.
I suspect we are not the first to run into this, so I think there should be a solution.

Thanks for looking into it.

**Comment by ryukau** [comment]
I found that hierarchy info can be obtained with faust's `-xml` or `-json` options.

Duplication and convension issues are now solved.

I'll make some workaround to the character issue. Currently using a following function to format label.

```python3
# Python3
def format_name(name: str):
    nm = name.replace(" ", "").replace("-", "_").replace("/", "_")
    return nm.capitalize()
```

The result looks like this.

```
CzsynthDStereoL_roffsetOscillatorCz_pmCzIndexModulationsourcesEnvelopesEnv0
```

**Comment by magnetophon** [comment]
> I'm planning to use parameter label as C++ identifier. So it would be nice to use only a-zA-Z0-9_ for label.

reminder.

**Comment by magnetophon** [comment]
After having a second thought, maybe it's better if we leave the names human friendly in the faust code, and you make them cpp compatible with your python code.

If that is not OK with you or if there are names that you still want to change, please re-open the issue.

**Comment by ryukau** [comment]
I just have one thing. Please avoid using `/`. Address in json data uses `/` as delimiter:

```json
{
  "type": "hslider",
  "label": "ab/cd",
  "address": "/CZsynth/global/stereo/main/vector/ab/cd/macro_0_-_1/macro_0/ab/cd"
}
```

So if `/` is used in label, I can't retrieve label from address, which is convenient information.

**Comment by magnetophon** [comment]
Done in https://github.com/magnetophon/DigiDrie/commit/b71ce7d8bb146c89449676cd28404c9bb4ff7a6f
